import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { CE_Sidebar } from "./$element/client.sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased w-full`}>
        <CE_Sidebar />

        <div className="ml-64 min-h-screen flex flex-col justify-center items-center px-4 bg-green-900 text-white transition-all duration-1000 ease-in-out">
          {children}
        </div>
      </body>
    </html>
  );
}
